---
version: "3.8"

# TODO: rename [webapp] to actual appname

# NOTE: might need to execute in case of db like neondb:
# query: GRANT ALL PRIVILEGES ON SCHEMA public TO "your-db-user";
# to allow directus to change schema and modify tables.

networks:
  webapp-proxy:
  proxy:
    external: true

services:

  webapp-proxy:
    container_name: webapp-proxy
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    networks:
      - webapp-proxy
      - proxy

  webapp:
    container_name: webapp
    build:
      context: .
      target: runner
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    networks:
      - webapp-proxy
