import type { Metadata } from "next";
import "./styles.css";

import { cookies } from "next/headers";
import { LayoutProps } from "@/lib/types";
import { cn } from "@/lib/utils";
import { defaultTheme } from "@/lib/themes";

export default function RootLayout({ children }: LayoutProps) {
	const cookieStore = cookies();
	const theme = cookieStore.get("theme")?.value || defaultTheme;

	return (
		<html lang="en" data-theme={theme}>
			<body
				className={cn(
					"bg-base-100 text-base-content",
					"antialiased transition-all duration-300 ease-in-out"
				)}
			>
				{/**/}
				{children}
			</body>
		</html>
	);
}

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
